export const knowledgeSources = [
  {
    id: 'sat-nomina-guia',
    name: 'SAT - Complemento de nomina CFDI',
    url: 'https://www.sat.gob.mx/consultas/97722/comprobante-de-nomina',
    publisher: 'SAT',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'sat-complemento-nomina',
    name: 'SAT - Complemento de nomina',
    url: 'http://omawww.sat.gob.mx/tramitesyservicios/Paginas/complemento_nomina.htm',
    publisher: 'SAT',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'diputados-lisr',
    name: 'Camara de Diputados - Ley del Impuesto sobre la Renta',
    url: 'https://www.diputados.gob.mx/LeyesBiblio/pdf/LISR.pdf',
    publisher: 'Camara de Diputados',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'diputados-lss',
    name: 'Camara de Diputados - Ley del Seguro Social',
    url: 'https://www.diputados.gob.mx/LeyesBiblio/pdf/LSS.pdf',
    publisher: 'Camara de Diputados',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'diputados-lft',
    name: 'Camara de Diputados - Ley Federal del Trabajo',
    url: 'https://www.diputados.gob.mx/LeyesBiblio/pdf/LFT.pdf',
    publisher: 'Camara de Diputados',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'diputados-infonavit',
    name: 'Camara de Diputados - Ley del INFONAVIT',
    url: 'https://www.diputados.gob.mx/LeyesBiblio/pdf/LIFNVT.pdf',
    publisher: 'Camara de Diputados',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'dof-subsidio-empleo-2024',
    name: 'DOF - Subsidio para el empleo 2024',
    url: 'https://www.dof.gob.mx/nota_detalle.php?codigo=5725287&fecha=01/05/2024',
    publisher: 'Diario Oficial de la Federacion',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'condusef-estado-cuenta-tdc',
    name: 'CONDUSEF - Estado de Cuenta Universal de Tarjeta de Credito',
    url: 'https://nuevoestadodecuentadetdc.condusef.gob.mx/',
    publisher: 'CONDUSEF',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'condusef-glosario-tdc',
    name: 'CONDUSEF - Glosario de tarjetas de credito',
    url: 'https://tarjetas.condusef.gob.mx/glosario.php',
    publisher: 'CONDUSEF',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'cfpb-credit-card-key-terms',
    name: 'CFPB - Credit card key terms',
    url: 'https://www.consumerfinance.gov/consumer-tools/credit-cards/answers/key-terms/',
    publisher: 'Consumer Financial Protection Bureau',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'banxico-cep',
    name: 'Banxico - Comprobante Electronico de Pago SPEI',
    url: 'https://www.banxico.org.mx/cep/',
    publisher: 'Banco de Mexico',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'banxico-comparador-creditos',
    name: 'Banxico - Comparador de creditos',
    url: 'https://comparador.banxico.org.mx/ComparadorCrediticio/',
    publisher: 'Banco de Mexico',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'imss-sbc',
    name: 'IMSS - Salario Base de Cotizacion',
    url: 'https://www.imss.gob.mx/',
    publisher: 'IMSS',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'infonavit-aportaciones',
    name: 'INFONAVIT - Credito y aportaciones',
    url: 'https://portalmx.infonavit.org.mx/',
    publisher: 'INFONAVIT',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'imss-nss',
    name: 'IMSS - Asignacion o localizacion de NSS',
    url: 'https://www.imss.gob.mx/tramites/imss02008',
    publisher: 'IMSS',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'gob-curp',
    name: 'Gobierno de Mexico - Consulta CURP',
    url: 'https://www.gob.mx/curp/',
    publisher: 'Gobierno de Mexico',
    retrievedAt: '2026-06-20',
  },
  {
    id: 'nu-mx-products',
    name: 'Nu Mexico - Productos, transparencia y respaldo regulatorio',
    url: 'https://nu.com.mx/',
    publisher: 'Nu Mexico',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'gbm-products',
    name: 'GBM - Soluciones de inversion y productos',
    url: 'https://gbm.com/',
    publisher: 'GBM',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'cetesdirecto-productos',
    name: 'Cetesdirecto - Productos de inversion gubernamental',
    url: 'https://www.cetesdirecto.com/sites/portal/productos.cetesdirecto',
    publisher: 'Cetesdirecto / Gobierno de Mexico',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'consar-cuenta-individual',
    name: 'CONSAR - Cuenta individual Afore',
    url: 'https://www.consar.gob.mx/gobmx/aplicativo/catsar/Principal/TramiteExt.aspx?idTramite=4&PAG_ACTUAL=/gobmx/aplicativo/catsar/Principal/InicioExt.aspx',
    publisher: 'CONSAR',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'consar-catalogo-tramites',
    name: 'CONSAR - Catalogo de tramites de cuenta individual',
    url: 'https://www.consar.gob.mx/gobmx/aplicativo/catsar/Principal/InicioExt.aspx',
    publisher: 'CONSAR',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'sat-cfdi-verificacion',
    name: 'SAT - Verificacion de comprobantes fiscales digitales',
    url: 'https://verificacfdi.facturaelectronica.sat.gob.mx/',
    publisher: 'SAT',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'sat-catalogos-cfdi',
    name: 'SAT - Catalogos CFDI',
    url: 'https://www.sat.gob.mx/consultas/53693/catalogos-del-cfdi',
    publisher: 'SAT',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'condusef-sipres',
    name: 'CONDUSEF - Sistema de Registro de Prestadores de Servicios Financieros',
    url: 'https://webapps.condusef.gob.mx/SIPRES/jsp/pub/index.jsp',
    publisher: 'CONDUSEF',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'condusef-buro-entidades',
    name: 'CONDUSEF - Buro de Entidades Financieras',
    url: 'https://www.buro.gob.mx/',
    publisher: 'CONDUSEF',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'nu-credito',
    name: 'Nu Mexico - Tarjeta de credito Nu',
    url: 'https://nu.com.mx/credito/',
    publisher: 'Nu Mexico',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'nu-cuenta',
    name: 'Nu Mexico - Cuenta Nu y Cajitas',
    url: 'https://nu.com.mx/cuenta/',
    publisher: 'Nu Mexico',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'nu-gat',
    name: 'Nu Mexico - GAT y rendimientos de Cajitas',
    url: 'https://nu.com.mx/gat/',
    publisher: 'Nu Mexico',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'nu-contratos',
    name: 'Nu Mexico - Contratos y formatos legales',
    url: 'https://nu.com.mx/contratos/',
    publisher: 'Nu Mexico',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'gbm-smart-cash',
    name: 'GBM - Smart Cash',
    url: 'https://gbm.com/smart-cash/',
    publisher: 'GBM',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'gbm-trading',
    name: 'GBM - Trading en Mexico y Estados Unidos',
    url: 'https://gbm.com/trading/',
    publisher: 'GBM',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'gbm-contrato-intermediacion',
    name: 'GBM - Contrato de intermediacion bursatil',
    url: 'https://gbm.com/wp-content/uploads/2024/11/Contrato-de-Intermediacion-Bursatil-V0620-1.pdf',
    publisher: 'GBM',
    retrievedAt: '2026-06-21',
  },
  {
    id: 'bmv-market-infrastructure',
    name: 'Grupo BMV - Mercado, brokers, regulacion e Indeval',
    url: 'https://www.bmv.com.mx/',
    publisher: 'Grupo BMV',
    retrievedAt: '2026-06-22',
  },
]

const knowledgeFieldAliases = {
  account_last4: ['accountLast4'],
  amount: ['amount'],
  annual_fee: ['annualFee'],
  annual_fixed_rate: ['annualYieldPercent'],
  annual_rate: ['annualYieldPercent'],
  annual_rate_percent: ['annualYieldPercent'],
  available_credit: ['availableCredit'],
  available_to_invest: ['availableToInvest'],
  balance: ['cashBalance'],
  bank: ['bankName'],
  beneficiary_account: ['speiBeneficiaryAccountLast4'],
  benefits_factor: ['benefitsFactor'],
  box_type: ['savingsProduct'],
  calculation_date: ['yieldCalculationDate'],
  card_last4: ['cardLast4'],
  case_folio: ['caseFolio'],
  cash_balance: ['cashBalance'],
  category_review_required: ['reviewRequired'],
  certification_status: ['cfdiStatus'],
  cfdi_uuid: ['uuid'],
  charge_description: ['chargeDescription'],
  closing_balance: ['closingBalance'],
  commission: ['commissionsAmount'],
  commissions: ['commissionsAmount'],
  concept_code: ['conceptCode'],
  credit_limit: ['creditLimit'],
  credit_number: ['creditNumber'],
  credit_utilization: ['creditUtilization'],
  currency: ['currency'],
  curp: ['employeeCurpSuffix'],
  cutoff_date: ['cutoffDate'],
  daily_return: ['dailyReturn'],
  daily_salary: ['dailySalary'],
  deductibility_hint: ['deductibilityHint'],
  detected_instruments: ['detectedInstruments'],
  discount_amount: ['infonavitWithheld'],
  due_date: ['dueDate'],
  employee_contribution: ['imssWithheld'],
  employee_name: ['employeeName'],
  employee_rfc: ['employeeRfcSuffix'],
  employer_registration: ['employerRegistrationSuffix'],
  employer_rfc: ['employerRfcSuffix'],
  entity_name: ['entityName'],
  entity_type: ['entityType'],
  exempt_amount: ['exemptAmount'],
  execution_price: ['price'],
  fee_amount: ['feesAmount'],
  fee_type: ['feeType'],
  final_resolution: ['finalResolution'],
  fiscal_zip_code: ['fiscalZipCode'],
  fund_name: ['fundName'],
  gbm_account_id: ['accountLast4'],
  gross_pay: ['grossPay'],
  installment_number: ['installmentNumber'],
  installment_total: ['installmentTotal'],
  instrument_symbol: ['instrumentSymbol'],
  interest_rate: ['ordinaryAnnualRate'],
  issuer_bank: ['speiIssuerInstitution'],
  issuer_rfc: ['issuerRfcSuffix'],
  linked_transaction_id: ['linkedTransactionId'],
  liquidity_window: ['liquidity'],
  lock_days: ['frozenTermDays'],
  merchant_confidence: ['merchantConfidence'],
  merchant_suffix: ['merchantSuffix'],
  minimum_amount: ['minimumAmount'],
  minimum_payment: ['minimumPayment'],
  minimum_payment_with_deferred: ['minimumPaymentWithDeferred'],
  monthly_deposit_limit_udis: ['monthlyDepositLimitUdis'],
  monthly_income_limit: ['monthlyIncomeLimit'],
  monthly_payment: ['monthlyPayment'],
  net_pay: ['netIncome'],
  nominal_gat: ['nominalGatPercent'],
  nominal_gat_percent: ['nominalGatPercent'],
  no_interest_payment: ['noInterestPayment'],
  normalized_merchant: ['merchant'],
  nss: ['employeeNssSuffix'],
  operation_date: ['operationDate'],
  order_type: ['orderType'],
  ordinary_annual_rate: ['ordinaryAnnualRate'],
  original_amount: ['originalAmount'],
  other_payment_type: ['otherPaymentType'],
  outstanding_balance: ['outstandingBalance'],
  pay_date: ['paymentDate'],
  pay_period: ['periodStart', 'periodEnd'],
  payment_account_last4: ['paymentAccountLast4'],
  payment_processor: ['paymentProcessor'],
  payment_reference: ['paymentReference'],
  payroll_complement_version: ['payrollComplementVersion'],
  period_end: ['periodEnd'],
  period_return: ['periodReturn'],
  period_start: ['periodStart'],
  portfolio_value: ['portfolioValue'],
  posting_date: ['postingDate'],
  price: ['price'],
  product_name: ['savingsProduct'],
  product_service_code: ['productServiceCode'],
  protection_limit_udis: ['protectionLimitUdis'],
  quantity: ['quantity'],
  rate_type: ['rateType'],
  raw_descriptor_redacted: ['rawDescriptorRedacted'],
  real_gat: ['realGatPercent'],
  real_gat_percent: ['realGatPercent'],
  receiver_bank: ['speiReceiverInstitution'],
  receiver_rfc: ['receiverRfcSuffix'],
  reconciliation_difference: ['cardReconciliationDifference'],
  reference_number: ['speiReferenceNumber'],
  regulator: ['regulator'],
  reinvestment_instruction: ['reinvestmentInstruction'],
  report_date: ['reportDate'],
  required_installment: ['requiredInstallment'],
  requires_review: ['cardReconciliationStatus'],
  review_required: ['reviewRequired'],
  revolving_balance: ['revolvingBalance'],
  rule_version: ['ruleVersion'],
  sbc: ['baseContributionSalary'],
  sdi: ['dailyIntegratedSalary'],
  series: ['series'],
  settlement_date: ['settlementDate'],
  settlement_time: ['settlementWindow'],
  settlement_window: ['settlementWindow'],
  shares: ['titleCount'],
  side: ['side'],
  sipres_status: ['sipresStatus'],
  source_account: ['sourceAccount'],
  spei_tracking_key: ['speiTraceKey'],
  statement_date: ['statementDate'],
  statement_period: ['periodStart', 'periodEnd'],
  status: ['status'],
  subsidy_amount: ['employmentSubsidyAmount'],
  tax_object: ['taxObject'],
  tax_regime: ['taxRegime'],
  taxable_amount: ['taxableAmount'],
  taxable_income: ['totalPerceptionsTaxable'],
  temporary_credit: ['temporaryCredit'],
  term_months: ['termMonths'],
  term_days: ['termDays'],
  ticker: ['instrumentSymbol'],
  total_cost: ['totalCost'],
  total_debt_balance: ['totalDebtBalance'],
  total_deductions: ['totalDeducciones'],
  total_other_payments: ['totalOtrosPagos'],
  total_perceptions: ['totalPercepciones'],
  tracking_key: ['speiTraceKey'],
  trade_date: ['tradeDate'],
  transfer_classification: ['movementType'],
  uma_value: ['umaValue'],
  unit_code: ['unitCode'],
  unrealized_gain: ['unrealizedGain'],
  valid_from: ['validFrom'],
  valid_until: ['yieldValidUntil'],
  valuation_date: ['valuationDate'],
  vat_amount: ['vatAmount'],
  verification_source: ['verificationSource'],
  withheld_amount: ['isrWithheld'],
  xml_file_size: ['xmlFileSize'],
}

function toCamelField(field) {
  return field.replace(/_([a-z0-9])/g, (_, char) => char.toUpperCase())
}

function normalizeKnowledgeFields(fields) {
  return [...new Set(fields.flatMap((field) => knowledgeFieldAliases[field] ?? [toCamelField(field)]))]
}

function normalizeKnowledgeEntry(entry) {
  return {
    ...entry,
    fields: normalizeKnowledgeFields(entry.fields),
  }
}

const rawKnowledgeEntries = [
  {
    id: 'mx-payroll-isr',
    domain: 'payroll_tax_mx',
    title: 'ISR retenido',
    aliases: ['ISR', 'Impuesto Sobre la Renta', 'retencion ISR', 'isr retenido'],
    summary: 'Impuesto federal retenido por el patron sobre ingresos gravados de nomina. En el recibo suele aparecer como deduccion.',
    patterns: ['\\bISR\\b', 'impuesto\\s+sobre\\s+la\\s+renta', 'retenci[oó]n\\s+isr'],
    fields: ['taxable_income', 'withheld_amount', 'pay_period', 'employer_rfc', 'employee_rfc'],
    sourceIds: ['sat-nomina-guia', 'diputados-lisr'],
    confidence: 0.86,
  },
  {
    id: 'mx-payroll-cfdi',
    domain: 'payroll_cfdi_mx',
    title: 'CFDI de nomina',
    aliases: ['CFDI nomina', 'recibo de nomina', 'comprobante de nomina', 'tipo comprobante N'],
    summary: 'Comprobante fiscal que documenta pago de salarios. Debe conservar UUID, fecha de timbrado, emisor, receptor, periodo e importes.',
    patterns: ['cfdi\\s+de\\s+n[oó]mina', 'recibo\\s+de\\s+n[oó]mina', 'tipo\\s+comprobante\\s+N', 'uuid'],
    fields: ['uuid', 'pay_date', 'employer_rfc', 'employee_rfc', 'total', 'payroll_complement_version'],
    sourceIds: ['sat-nomina-guia', 'sat-complemento-nomina'],
    confidence: 0.9,
  },
  {
    id: 'mx-payroll-cfdi-status',
    domain: 'payroll_cfdi_mx',
    title: 'Estatus y verificacion de CFDI',
    aliases: ['estatus CFDI', 'verificar CFDI', 'folio fiscal', 'vigente', 'cancelado'],
    summary: 'El SAT permite verificar si un CFDI fue certificado por folio fiscal, RFC emisor/receptor o archivo XML. La app debe conservar UUID/RFCs y marcar comprobantes no verificables para revision.',
    patterns: ['estatus\\s+cfdi', 'verificar\\s+cfdi', 'folio\\s+fiscal', 'vigente', 'cancelad[oa]', 'certificado\\s+por\\s+el\\s+sat'],
    fields: ['uuid', 'issuer_rfc', 'receiver_rfc', 'certification_status', 'xml_file_size', 'verification_source'],
    sourceIds: ['sat-cfdi-verificacion', 'sat-nomina-guia'],
    confidence: 0.88,
  },
  {
    id: 'mx-payroll-net-reconciliation',
    domain: 'payroll_cfdi_mx',
    title: 'Conciliacion neta de nomina',
    aliases: ['neto pagado', 'total percepciones', 'total deducciones', 'total otros pagos'],
    summary: 'La nomina debe reconciliar percepciones, deducciones y otros pagos contra el total neto para evitar capturar ingresos duplicados o incompletos.',
    patterns: ['neto\\s+pagado', 'total\\s+percepciones', 'total\\s+deducciones', 'total\\s+otros\\s+pagos'],
    fields: ['gross_pay', 'total_perceptions', 'total_deductions', 'total_other_payments', 'net_pay', 'pay_period'],
    sourceIds: ['sat-nomina-guia', 'sat-complemento-nomina'],
    confidence: 0.86,
  },
  {
    id: 'mx-payroll-imss',
    domain: 'payroll_tax_mx',
    title: 'Cuota IMSS',
    aliases: ['IMSS', 'cuota obrera', 'seguro social', 'NSS'],
    summary: 'Retencion asociada a seguridad social. Conviene relacionarla con NSS, salario base de cotizacion y periodo.',
    patterns: ['\\bIMSS\\b', 'cuota\\s+obrera', 'seguro\\s+social', '\\bNSS\\b'],
    fields: ['nss', 'sbc', 'employee_contribution', 'pay_period'],
    sourceIds: ['imss-sbc', 'imss-nss', 'sat-nomina-guia', 'diputados-lss'],
    confidence: 0.82,
  },
  {
    id: 'mx-payroll-infonavit',
    domain: 'payroll_tax_mx',
    title: 'Descuento INFONAVIT',
    aliases: ['INFONAVIT', 'credito infonavit', 'descuento vivienda'],
    summary: 'Descuento de nomina relacionado con credito de vivienda o aportaciones al fondo de vivienda.',
    patterns: ['INFONAVIT', 'cr[eé]dito\\s+infonavit', 'descuento\\s+vivienda'],
    fields: ['credit_number', 'discount_amount', 'pay_period', 'employer_rfc'],
    sourceIds: ['infonavit-aportaciones', 'sat-nomina-guia', 'diputados-infonavit'],
    confidence: 0.78,
  },
  {
    id: 'mx-payroll-subsidio-empleo',
    domain: 'payroll_tax_mx',
    title: 'Subsidio para el empleo',
    aliases: ['subsidio al empleo', 'subsidio para el empleo', 'subsidio causado', 'subsidio aplicado'],
    summary: 'Beneficio fiscal versionado para ciertos trabajadores. Desde el decreto DOF 01/05/2024 debe modelarse por vigencia y no como constante fija.',
    patterns: ['subsidio\\s+(al|para\\s+el)\\s+empleo', 'subsidio\\s+causado', 'subsidio\\s+aplicado'],
    fields: ['subsidy_amount', 'monthly_income_limit', 'uma_value', 'rule_version', 'valid_from'],
    sourceIds: ['dof-subsidio-empleo-2024', 'sat-complemento-nomina'],
    confidence: 0.82,
  },
  {
    id: 'mx-payroll-percepcion',
    domain: 'payroll_cfdi_mx',
    title: 'Percepcion de nomina',
    aliases: ['percepcion', 'sueldo', 'salario', 'prima vacacional', 'aguinaldo'],
    summary: 'Ingreso pagado al trabajador. Puede ser gravado, exento o mixto dentro del complemento de nomina.',
    patterns: ['percepci[oó]n', 'sueldo', 'salario', 'prima\\s+vacacional', 'aguinaldo'],
    fields: ['concept_code', 'taxable_amount', 'exempt_amount', 'pay_period'],
    sourceIds: ['sat-nomina-guia', 'sat-complemento-nomina', 'diputados-lisr'],
    confidence: 0.84,
  },
  {
    id: 'mx-payroll-deduccion',
    domain: 'payroll_cfdi_mx',
    title: 'Deduccion de nomina',
    aliases: ['deduccion', 'retencion', 'descuento'],
    summary: 'Monto restado al pago bruto: impuestos, seguridad social, credito de vivienda u otros descuentos.',
    patterns: ['deducci[oó]n', 'retenci[oó]n', 'descuento'],
    fields: ['concept_code', 'amount', 'pay_period'],
    sourceIds: ['sat-nomina-guia', 'sat-complemento-nomina'],
    confidence: 0.84,
  },
  {
    id: 'mx-payroll-otros-pagos',
    domain: 'payroll_cfdi_mx',
    title: 'Otros pagos de nomina',
    aliases: ['otros pagos', 'otro pago', 'viaticos', 'compensacion saldo a favor'],
    summary: 'Nodo del complemento de nomina para importes que no son percepcion ordinaria ni deduccion, como subsidio al empleo o ciertos viaticos segun catalogo.',
    patterns: ['otros\\s+pagos', 'otro\\s+pago', 'vi[aá]ticos', 'compensaci[oó]n\\s+saldo\\s+a\\s+favor'],
    fields: ['other_payment_type', 'concept_code', 'amount', 'catalog_version'],
    sourceIds: ['sat-complemento-nomina'],
    confidence: 0.78,
  },
  {
    id: 'mx-person-rfc',
    domain: 'identity_tax_mx',
    title: 'RFC',
    aliases: ['RFC', 'registro federal de contribuyentes'],
    summary: 'Clave fiscal usada por SAT para identificar contribuyentes. En nomina aparece para patron y trabajador.',
    patterns: ['\\bRFC\\b', 'registro\\s+federal\\s+de\\s+contribuyentes'],
    fields: ['employer_rfc', 'employee_rfc', 'tax_regime', 'fiscal_zip_code'],
    sourceIds: ['sat-nomina-guia'],
    confidence: 0.84,
  },
  {
    id: 'mx-person-curp',
    domain: 'identity_mx',
    title: 'CURP',
    aliases: ['CURP', 'clave unica de registro de poblacion'],
    summary: 'Identificador poblacional oficial. En CFDI de nomina ayuda a reconocer al trabajador, pero debe tratarse como dato personal.',
    patterns: ['\\bCURP\\b', 'clave\\s+unica\\s+de\\s+registro\\s+de\\s+poblaci[oó]n'],
    fields: ['curp', 'employee_name', 'employee_rfc'],
    sourceIds: ['gob-curp', 'sat-complemento-nomina'],
    confidence: 0.84,
  },
  {
    id: 'mx-person-nss',
    domain: 'identity_social_security_mx',
    title: 'NSS',
    aliases: ['NSS', 'numero de seguridad social', 'número de seguridad social'],
    summary: 'Numero unico de seguridad social del trabajador. Es clave para relacionar recibos de nomina con cuotas IMSS.',
    patterns: ['\\bNSS\\b', 'n[uú]mero\\s+de\\s+seguridad\\s+social'],
    fields: ['nss', 'employee_name', 'sbc', 'employer_registration'],
    sourceIds: ['imss-nss', 'sat-complemento-nomina'],
    confidence: 0.86,
  },
  {
    id: 'mx-payroll-sbc',
    domain: 'payroll_social_security_mx',
    title: 'Salario Base de Cotizacion',
    aliases: ['SBC', 'salario base de cotizacion', 'salario base de cotización'],
    summary: 'Base para cuotas del IMSS. Debe versionarse y conservar trazabilidad porque depende de integracion y exclusiones legales.',
    patterns: ['\\bSBC\\b', 'salario\\s+base\\s+de\\s+cotizaci[oó]n'],
    fields: ['sbc', 'uma_value', 'valid_from', 'employee_contribution', 'employer_registration'],
    sourceIds: ['imss-sbc', 'diputados-lss', 'sat-complemento-nomina'],
    confidence: 0.82,
  },
  {
    id: 'mx-payroll-sdi',
    domain: 'payroll_social_security_mx',
    title: 'Salario Diario Integrado',
    aliases: ['SDI', 'salario diario integrado'],
    summary: 'Concepto ligado al salario integrado. No debe asumirse identico al SBC sin validar regla, fuente y periodo.',
    patterns: ['\\bSDI\\b', 'salario\\s+diario\\s+integrado'],
    fields: ['sdi', 'daily_salary', 'benefits_factor', 'valid_from'],
    sourceIds: ['diputados-lft', 'sat-complemento-nomina'],
    confidence: 0.78,
  },
  {
    id: 'mx-card-minimum-payment',
    domain: 'credit_card_mx',
    title: 'Pago minimo',
    aliases: ['pago minimo', 'pago requerido minimo'],
    summary: 'Monto minimo para mantener la cuenta al corriente. No equivale al pago para no generar intereses.',
    patterns: ['pago\\s+m[ií]nimo', 'pago\\s+requerido\\s+m[ií]nimo'],
    fields: ['minimum_payment', 'due_date', 'statement_period'],
    sourceIds: ['condusef-estado-cuenta-tdc', 'condusef-glosario-tdc'],
    confidence: 0.9,
  },
  {
    id: 'mx-card-no-interest-payment',
    domain: 'credit_card_mx',
    title: 'Pago para no generar intereses',
    aliases: ['pago para no generar intereses', 'PPNGI'],
    summary: 'Monto a pagar antes de la fecha limite para evitar intereses ordinarios sobre cargos regulares.',
    patterns: ['pago\\s+para\\s+no\\s+generar\\s+inter[eé]s', 'no\\s+generar\\s+inter[eé]s'],
    fields: ['no_interest_payment', 'due_date', 'revolving_balance'],
    sourceIds: ['condusef-estado-cuenta-tdc', 'condusef-glosario-tdc'],
    confidence: 0.9,
  },
  {
    id: 'mx-card-cutoff-due-date',
    domain: 'credit_card_mx',
    title: 'Fecha de corte y fecha limite de pago',
    aliases: ['fecha de corte', 'fecha limite de pago', 'fecha límite de pago'],
    summary: 'La fecha de corte cierra el periodo del estado de cuenta; la fecha limite es el ultimo dia para pagar.',
    patterns: ['fecha\\s+de\\s+corte', 'fecha\\s+l[ií]mite\\s+de\\s+pago'],
    fields: ['cutoff_date', 'due_date', 'period_start', 'period_end'],
    sourceIds: ['condusef-estado-cuenta-tdc'],
    confidence: 0.88,
  },
  {
    id: 'mx-card-msi',
    domain: 'credit_card_mx',
    title: 'Meses sin intereses',
    aliases: ['MSI', 'meses sin intereses'],
    summary: 'Compra diferida a meses con tasa 0%. Debe distinguirse de compras diferidas con intereses.',
    patterns: ['\\bMSI\\b', 'mes(es)?\\s+sin\\s+inter[eé]s(es)?', 'a\\s+meses\\s+sin\\s+inter[eé]s'],
    fields: ['original_amount', 'installment_number', 'installment_total', 'required_installment', 'outstanding_balance'],
    sourceIds: ['condusef-estado-cuenta-tdc'],
    confidence: 0.88,
  },
  {
    id: 'mx-card-cat',
    domain: 'credit_card_mx',
    title: 'CAT y tasa anual',
    aliases: ['CAT', 'Costo Anual Total', 'tasa anual', 'tasa ordinaria'],
    summary: 'CAT ayuda a comparar costo total del credito; la tasa anual representa interes, pero no todos los costos.',
    patterns: ['\\bCAT\\b', 'Costo\\s+Anual\\s+Total', 'tasa\\s+(de\\s+)?inter[eé]s', 'tasa\\s+anual'],
    fields: ['cat_percent', 'ordinary_annual_rate', 'rate_type'],
    sourceIds: ['banxico-comparador-creditos', 'condusef-glosario-tdc'],
    confidence: 0.86,
  },
  {
    id: 'mx-card-universal-statement-fields',
    domain: 'credit_card_mx',
    title: 'Estado de cuenta universal TDC',
    aliases: ['estado de cuenta universal', 'periodo', 'saldo deudor total', 'nivel de uso', 'credito disponible'],
    summary: 'El estado universal de tarjeta debe extraer periodo, corte, fecha limite, pago minimo, pago para no generar intereses, CAT, tasa, limite, disponible y saldo deudor como campos separados.',
    patterns: [
      'estado\\s+de\\s+cuenta\\s+universal',
      'periodo\\s+del',
      'saldo\\s+deudor\\s+total',
      'nivel\\s+de\\s+uso',
      'cr[eé]dito\\s+disponible',
    ],
    fields: [
      'statement_period',
      'cutoff_date',
      'due_date',
      'minimum_payment',
      'minimum_payment_with_deferred',
      'no_interest_payment',
      'cat_percent',
      'ordinary_annual_rate',
      'credit_limit',
      'available_credit',
      'total_debt_balance',
    ],
    sourceIds: ['condusef-estado-cuenta-tdc', 'condusef-glosario-tdc', 'banxico-comparador-creditos'],
    confidence: 0.92,
  },
  {
    id: 'mx-card-payment-scenarios',
    domain: 'credit_card_mx',
    title: 'Escenarios de pago de tarjeta',
    aliases: ['escenarios de pago', 'pago minimo x2', 'pago minimo x5', 'meses para liquidar', 'intereses estimados'],
    summary: 'La matriz de pagos del estado de cuenta permite comparar pago minimo, pago duplicado, pago quintuplicado o no aplicable para estimar meses, intereses y ahorro por adelantar pagos.',
    patterns: [
      'escenarios?\\s+de\\s+pago',
      'pago\\s+m[ií]nimo\\s*(x|por)?\\s*2',
      'pago\\s+m[ií]nimo\\s*(x|por)?\\s*5',
      'meses\\s+para\\s+liquidar',
      'inter[eé]s(?:es)?\\s+estimad',
    ],
    fields: [
      'cardPaymentScenarios',
      'cardPaymentScenarioRows',
      'scenarioName',
      'monthlyPayment',
      'monthsToPayoff',
      'estimatedInterest',
      'estimatedTotalCost',
      'cardLowestInterestScenario',
      'cardLowestEstimatedInterest',
      'cardMaxInterestSavings',
    ],
    sourceIds: ['condusef-estado-cuenta-tdc', 'banxico-comparador-creditos'],
    confidence: 0.86,
  },
  {
    id: 'mx-card-statement-reconciliation',
    domain: 'credit_card_mx',
    title: 'Conciliacion matematica de tarjeta',
    aliases: ['conciliacion de tarjeta', 'saldo anterior mas cargos menos pagos', 'diferencia de estado', 'cuadre de tarjeta'],
    summary: 'Antes de poblar el dashboard, el parser debe cuadrar saldo anterior, cargos, diferidos, IVA/intereses/comisiones, pagos y saldo actual. Si no cuadra, el documento queda en revision. APR/interes, creditos/pagos y periodo de gracia deben quedar separados para evitar confundir costo de financiamiento con consumo.',
    patterns: [
      'saldo\\s+anterior',
      'saldo\\s+actual',
      'total\\s+de\\s+cargos',
      'total\\s+de\\s+abonos',
      'diferencia\\s+de\\s+estado',
      'conciliaci[oó]n',
    ],
    fields: [
      'previous_balance',
      'new_charges',
      'deferred_amortization',
      'interest_amount',
      'vat_amount',
      'fees_amount',
      'payments_amount',
      'current_balance',
      'reconciliation_difference',
      'requires_review',
    ],
    sourceIds: ['condusef-estado-cuenta-tdc', 'condusef-glosario-tdc', 'cfpb-credit-card-key-terms'],
    confidence: 0.88,
  },
  {
    id: 'mx-card-deferred-installments',
    domain: 'credit_card_mx',
    title: 'Parcialidades MSI/MCI',
    aliases: ['parcialidad', '2/6', '3/12', 'saldo pendiente diferido', 'monto original diferido'],
    summary: 'Una compra diferida debe conservar monto original, saldo pendiente, parcialidad actual/total, pago requerido, tasa si aplica, interes, IVA y compromiso mensual.',
    patterns: [
      '\\b\\d{1,2}\\s*/\\s*\\d{1,2}\\b',
      'parcialidad',
      'saldo\\s+pendiente\\s+diferid',
      'monto\\s+original',
      'pago\\s+requerido',
    ],
    fields: [
      'merchant',
      'original_amount',
      'outstanding_balance',
      'installment_number',
      'installment_total',
      'required_installment',
      'rate_percent',
      'interest_amount',
      'vat_amount',
      'monthly_commitment',
    ],
    sourceIds: ['condusef-estado-cuenta-tdc', 'nu-credito'],
    confidence: 0.88,
  },
  {
    id: 'mx-card-amex-account-activity-csv',
    domain: 'credit_card_mx',
    title: 'CSV Account Activity AMEX Mexico',
    aliases: ['Account Activity', 'American Express CSV', 'Fecha de Compra', 'Aparece en su Estado de Cuenta como', 'Monto en moneda extranjera'],
    summary: 'El CSV de actividad AMEX Mexico debe mapear fecha, fecha de compra, descripcion visible, cuenta enmascarada, importe, moneda extranjera, tipo de cambio, pais y referencia sin guardar titular, cuenta completa o direccion por defecto.',
    patterns: [
      'account\\s+activity',
      'fecha\\s+de\\s+compra',
      'aparece\\s+en\\s+su\\s+estado\\s+de\\s+cuenta',
      'monto\\s+en\\s+moneda\\s+extranjera',
      'tipo\\s+de\\s+cambio',
    ],
    fields: [
      'posting_date',
      'purchase_date',
      'statement_description',
      'card_last4',
      'amount',
      'foreign_amount',
      'exchange_rate',
      'country',
      'reference_hash',
      'privacy_redaction_required',
    ],
    sourceIds: ['condusef-estado-cuenta-tdc'],
    confidence: 0.82,
  },
  {
    id: 'mx-card-merchant-aggregator-resolution',
    domain: 'merchant_enrichment_mx',
    title: 'Agregadores de pago y comercio real',
    aliases: ['MercadoPago', 'Clip', 'Netpay', 'Zettle', 'Sr Pago', 'Toka', 'Compropago', 'agregador de pago'],
    summary: 'Los agregadores pueden aparecer como descriptor principal y ocultar el comercio real. La app debe separar procesador, sufijo de comercio y comercio normalizado para no clasificar mal el gasto.',
    patterns: ['mercado\\s*pago', '\\bclip\\b', 'netpay', 'zettle', 'sr\\.?\\s*pago', 'toka', 'compropago', 'agregador\\s+de\\s+pago'],
    fields: ['payment_processor', 'raw_descriptor_redacted', 'merchant_suffix', 'normalized_merchant', 'merchant_confidence', 'category_review_required'],
    sourceIds: ['condusef-buro-entidades'],
    confidence: 0.76,
  },
  {
    id: 'mx-card-fee-taxonomy',
    domain: 'credit_card_mx',
    title: 'Taxonomia de comisiones financieras',
    aliases: ['anualidad', 'reposicion', 'pago tardio', 'disposicion de efectivo', 'comision financiera'],
    summary: 'Anualidad, pago tardio, reposicion, disposicion de efectivo y otras comisiones se deben clasificar como costo financiero, no como consumo ordinario.',
    patterns: [
      'anualidad',
      'reposici[oó]n',
      'pago\\s+tard[ií]o',
      'disposici[oó]n\\s+de\\s+efectivo',
      'comisi[oó]n\\s+financiera',
      'iva\\s+comisi[oó]n',
    ],
    fields: ['fee_type', 'fee_amount', 'vat_amount', 'posting_date', 'financial_cost_category', 'ordinary_spend_excluded'],
    sourceIds: ['banxico-comparador-creditos', 'condusef-estado-cuenta-tdc', 'condusef-buro-entidades'],
    confidence: 0.84,
  },
  {
    id: 'mx-card-dispute-workflow',
    domain: 'credit_card_mx',
    title: 'Flujo de cargo no reconocido',
    aliases: ['cargo no reconocido', 'disputa', 'aclaracion', 'folio UNE', 'REDECO', 'REUNE'],
    summary: 'Una disputa debe capturar fecha de operacion, fecha de reporte, descripcion, folio, estatus, monto y reverso asociado; el cargo queda aislado hasta resolucion final.',
    patterns: ['cargo\\s+no\\s+reconocido', 'disputa', 'aclaraci[oó]n', 'folio\\s+une', 'redeco', 'reune', 'reverso'],
    fields: ['operation_date', 'report_date', 'case_folio', 'status', 'amount', 'linked_transaction_id', 'temporary_credit', 'final_resolution'],
    sourceIds: ['condusef-estado-cuenta-tdc', 'condusef-sipres', 'condusef-buro-entidades'],
    confidence: 0.86,
  },
  {
    id: 'mx-sat-cfdi-category-mapping',
    domain: 'tax_category_mx',
    title: 'Mapeo CFDI producto-servicio a categoria',
    aliases: ['ClaveProdServ', 'c_ClaveProdServ', 'unidad E48', 'catalogo CFDI', 'deducible'],
    summary: 'Las claves de producto/servicio y unidad del CFDI ayudan a enriquecer categorias, IVA y reportes fiscales; no deben sustituir la revision cuando el comercio o uso fiscal sea ambiguo.',
    patterns: ['clave\\s*prod\\s*serv', 'c_ClaveProdServ', '\\bE48\\b', 'cat[aá]logo\\s+cfdi', 'deducible', 'uso\\s+cfdi'],
    fields: ['cfdi_uuid', 'product_service_code', 'unit_code', 'tax_object', 'vat_amount', 'deductibility_hint', 'review_required'],
    sourceIds: ['sat-catalogos-cfdi', 'sat-cfdi-verificacion'],
    confidence: 0.82,
  },
  {
    id: 'mx-card-credit-limit-utilization',
    domain: 'credit_card_mx',
    title: 'Limite y utilizacion de tarjeta',
    aliases: ['limite de credito', 'linea de credito', 'credito disponible', 'saldo actual', 'utilizacion'],
    summary: 'El limite, credito disponible y saldo actual permiten calcular utilizacion de tarjeta. La app debe extraer estos campos sin inferir deuda solo por sumar movimientos.',
    patterns: ['l[ií]nea\\s+de\\s+cr[eé]dito', 'l[ií]mite\\s+de\\s+cr[eé]dito', 'cr[eé]dito\\s+disponible', 'saldo\\s+actual', 'utilizaci[oó]n'],
    fields: ['credit_limit', 'available_credit', 'current_balance', 'credit_utilization', 'statement_date'],
    sourceIds: ['condusef-estado-cuenta-tdc', 'banxico-comparador-creditos'],
    confidence: 0.88,
  },
  {
    id: 'mx-card-deferred-with-interest',
    domain: 'credit_card_mx',
    title: 'Compras diferidas y pagos fijos',
    aliases: ['compras diferidas', 'plan de pagos fijos', 'meses con intereses', 'diferir compra'],
    summary: 'Las compras diferidas y planes de pagos fijos tienen plazo, tasa o cargo adicional; deben separarse de MSI para no subestimar costo financiero.',
    patterns: ['compras?\\s+diferidas?', 'plan\\s+de\\s+pagos\\s+fijos', 'meses\\s+con\\s+inter[eé]s', 'diferir\\s+compra'],
    fields: ['original_amount', 'term_months', 'monthly_payment', 'total_cost', 'interest_rate', 'commission'],
    sourceIds: ['condusef-estado-cuenta-tdc', 'nu-credito'],
    confidence: 0.84,
  },
  {
    id: 'mx-card-fees-commissions',
    domain: 'credit_card_mx',
    title: 'Comisiones y anualidad',
    aliases: ['comision', 'comisión', 'anualidad', 'pago tardio', 'retiro de efectivo'],
    summary: 'Cargos por acceso, uso o penalizacion: anualidad, disposicion de efectivo, pago tardio u otras comisiones.',
    patterns: ['comisi[oó]n', 'anualidad', 'pago\\s+tard[ií]o', 'retiro\\s+de\\s+efectivo', 'disposici[oó]n\\s+de\\s+efectivo'],
    fields: ['fee_type', 'fee_amount', 'vat_amount', 'posting_date'],
    sourceIds: ['banxico-comparador-creditos', 'condusef-estado-cuenta-tdc'],
    confidence: 0.84,
  },
  {
    id: 'mx-card-unrecognized-charge',
    domain: 'credit_card_mx',
    title: 'Cargo no reconocido',
    aliases: ['cargo no reconocido', 'aclaracion', 'reclamacion'],
    summary: 'Movimiento reportado por el usuario como no reconocido. Debe conservar folio, estatus y monto.',
    patterns: ['cargo\\s+no\\s+reconocido', 'aclaraci[oó]n', 'reclamaci[oó]n', 'folio'],
    fields: ['case_folio', 'charge_description', 'amount', 'operation_date', 'status'],
    sourceIds: ['condusef-estado-cuenta-tdc'],
    confidence: 0.86,
  },
  {
    id: 'mx-spei-tracking-key',
    domain: 'bank_transfer_mx',
    title: 'SPEI y clave de rastreo',
    aliases: ['SPEI', 'clave de rastreo', 'CEP', 'referencia'],
    summary: 'Identificadores de transferencia interbancaria; Banxico CEP permite consultar con clave de rastreo, referencia y datos de pago.',
    patterns: ['\\bSPEI\\b', 'clave\\s+de\\s+rastreo', '\\bCEP\\b', 'referencia'],
    fields: ['tracking_key', 'reference_number', 'issuer_bank', 'receiver_bank', 'beneficiary_account', 'amount'],
    sourceIds: ['banxico-cep'],
    confidence: 0.88,
  },
  {
    id: 'mx-nu-savings-account',
    domain: 'savings_account_mx',
    title: 'Cuenta Nu y Cajitas',
    aliases: ['Cuenta Nu', 'Cajita Nu', 'cajitas', 'Nu Mexico', 'Nu México', 'SFP', 'Sofipo'],
    summary: 'Cuenta de ahorro/debito de Nu Mexico. Para estados de cuenta conviene extraer saldo, GAT/rendimiento, SPEI, movimientos y terminacion de cuenta sin guardar identificadores completos.',
    patterns: ['cuenta\\s+nu', 'cajita', 'nu\\s+m[eé]xico', '\\bSFP\\b', 'sofipo', 'ganancia\\s+anual\\s+total', '\\bGAT\\b'],
    fields: ['closing_balance', 'annual_yield_percent', 'spei_tracking_key', 'account_last4', 'deposits_total', 'withdrawals_total'],
    sourceIds: ['nu-mx-products', 'nu-cuenta', 'nu-gat', 'nu-contratos', 'banxico-cep'],
    confidence: 0.84,
  },
  {
    id: 'mx-nu-cajita-yield',
    domain: 'savings_account_mx',
    title: 'Cajitas Nu, GAT y ahorro congelado',
    aliases: ['Cajita Turbo', 'Cajitas Nu', 'Ahorro Congelado', 'GAT Nu', 'rendimiento diario Nu'],
    summary: 'Las Cajitas y Ahorro Congelado pueden tener tasa anual, GAT nominal, GAT real, vigencia y monto minimo. La app debe capturar rendimiento como dato versionado por fecha.',
    patterns: ['cajita\\s+turbo', 'cajitas?\\s+nu', 'ahorro\\s+congelado', 'gat\\s+nominal', 'gat\\s+real', 'tasa\\s+de\\s+rendimiento\\s+anual'],
    fields: ['box_type', 'nominal_gat', 'real_gat', 'annual_rate', 'lock_days', 'minimum_amount', 'valid_until'],
    sourceIds: ['nu-cuenta', 'nu-gat', 'nu-contratos'],
    confidence: 0.88,
  },
  {
    id: 'mx-nu-gat-nominal-real',
    domain: 'savings_account_mx',
    title: 'GAT nominal y GAT real en Nu',
    aliases: ['GAT nominal', 'GAT real', 'rendimiento antes de impuestos', 'rendimiento despues de inflacion', 'tasa rendimiento anual fija'],
    summary: 'Nu publica tasa anual fija, GAT nominal y GAT real por producto/plazo. La app debe capturar estos porcentajes por fecha de calculo y vigencia, sin tratarlos como valores permanentes.',
    patterns: ['gat\\s+nominal', 'gat\\s+real', 'rendimiento\\s+antes\\s+de\\s+impuestos', 'inflaci[oó]n\\s+estimada', 'tasa\\s+de\\s+rendimiento\\s+anual\\s+fija'],
    fields: ['annual_rate_percent', 'nominal_gat_percent', 'real_gat_percent', 'calculation_date', 'valid_until', 'product_name', 'term_days'],
    sourceIds: ['nu-gat', 'nu-cuenta'],
    confidence: 0.9,
  },
  {
    id: 'mx-nu-sofipo-protection',
    domain: 'savings_account_mx',
    title: 'Proteccion SOFIPO y limite en UDIs',
    aliases: ['SOFIPO', 'Fondo de Proteccion', '25,000 UDIs', 'Nu Mexico Financiera', 'SFP'],
    summary: 'Nu Mexico opera como SFP/SOFIPO supervisada; la proteccion y limites por UDIs deben quedar separados de liquidez y rendimiento en el analisis.',
    patterns: ['sofipo', '\\bSFP\\b', 'fondo\\s+de\\s+protecci[oó]n', '25,?000\\s+udis', 'nu\\s+m[eé]xico\\s+financiera'],
    fields: ['entity_name', 'entity_type', 'regulator', 'protection_limit_udis', 'monthly_deposit_limit_udis', 'sipres_status'],
    sourceIds: ['nu-cuenta', 'nu-gat', 'condusef-sipres', 'condusef-buro-entidades'],
    confidence: 0.86,
  },
  {
    id: 'mx-nu-credit-card',
    domain: 'credit_card_mx',
    title: 'Tarjeta Nu',
    aliases: ['Tarjeta Nu', 'Nu tarjeta', 'tarjeta morada', 'Nu credit card'],
    summary: 'Tarjeta de credito de Nu. Debe mapearse como tarjeta aunque el emisor aparezca como Nu Mexico y conservar pagos, limite, fecha de corte, fecha limite, pago minimo y pago para no generar intereses.',
    patterns: ['tarjeta\\s+nu', 'nu\\s+tarjeta', 'fecha\\s+de\\s+corte', 'pago\\s+para\\s+no\\s+generar', 'pago\\s+m[ií]nimo'],
    fields: ['cutoff_date', 'due_date', 'minimum_payment', 'no_interest_payment', 'credit_limit', 'current_balance'],
    sourceIds: ['nu-mx-products', 'nu-credito', 'nu-contratos', 'condusef-estado-cuenta-tdc', 'condusef-glosario-tdc'],
    confidence: 0.86,
  },
  {
    id: 'mx-nu-credit-card-terms',
    domain: 'credit_card_mx',
    title: 'CAT, tasa y comision de Tarjeta Nu',
    aliases: ['CAT Nu', 'tasa anual Nu', 'comision anual Nu', 'Tarjeta Nu sin anualidad'],
    summary: 'Nu publica CAT, tasa anual fija, comision anual y vigencia de oferta. La app debe guardar estos campos con fecha de calculo para comparacion y no como constantes.',
    patterns: ['cat\\s+promedio\\s+ponderado', 'tasa\\s+promedio\\s+ponderada\\s+anual', 'comisi[oó]n\\s+anual', 'vigencia\\s+de\\s+la\\s+oferta'],
    fields: ['cat_percent', 'annual_fixed_rate', 'annual_fee', 'offer_valid_from', 'offer_valid_to', 'calculation_date'],
    sourceIds: ['nu-credito', 'nu-contratos', 'condusef-buro-entidades'],
    confidence: 0.86,
  },
  {
    id: 'mx-nu-payment-methods',
    domain: 'credit_card_mx',
    title: 'Pago de Tarjeta Nu por SPEI',
    aliases: ['CLABE Nu', 'pagar con SPEI', 'como pagar Nu', '16 digitos tarjeta'],
    summary: 'Nu permite pagar con CLABE SPEI de 18 digitos o con los 16 digitos de la tarjeta. El analisis debe conservar solo terminaciones y referencias no sensibles.',
    patterns: ['clabe\\s+spei', 'c[oó]mo\\s+pagar', '16\\s+d[ií]gitos', 'transferencia\\s+electr[oó]nica', '\\bSPEI\\b'],
    fields: ['payment_account_last4', 'card_last4', 'payment_reference', 'bank', 'amount', 'due_date'],
    sourceIds: ['nu-credito', 'banxico-cep'],
    confidence: 0.82,
  },
  {
    id: 'mx-gbm-smart-cash',
    domain: 'investment_statement_mx',
    title: 'GBM Smart Cash',
    aliases: ['Smart Cash', 'GBM Smart Cash', 'GBM+', 'GBM Plus'],
    summary: 'Producto de liquidez de GBM. En documentos conviene extraer saldo/valor, rendimiento, moneda, movimientos de aportacion/retiro y cuenta relacionada.',
    patterns: ['smart\\s+cash', '\\bGBM\\+?\\b', 'gbm\\s+plus', 'rendimiento', 'saldo\\s+disponible'],
    fields: ['portfolio_value', 'cash_balance', 'period_return', 'annual_yield_percent', 'currency', 'account_last4'],
    sourceIds: ['gbm-products', 'gbm-smart-cash', 'gbm-contrato-intermediacion'],
    confidence: 0.84,
  },
  {
    id: 'mx-gbm-smart-cash-liquidity',
    domain: 'investment_statement_mx',
    title: 'Liquidez y moneda de Smart Cash',
    aliases: ['Smart Cash Pesos', 'Smart Cash Dolares', 'Smart Cash Dólares', 'liquidez 24 horas', 'CLABE GBM'],
    summary: 'Smart Cash puede estar en MXN o USD y tiene liquidez operativa. La app debe separar moneda, saldo, rendimiento diario y ventanas de retiro.',
    patterns: ['smart\\s+cash\\s+(pesos|d[oó]lares)', 'liquidez\\s+24\\s+horas', 'moneda\\s+(mxn|usd)', 'dep[oó]sitos\\s+con\\s+cuenta\\s+clabe'],
    fields: ['gbm_account_id', 'currency', 'balance', 'daily_return', 'liquidity_window', 'settlement_time'],
    sourceIds: ['gbm-smart-cash', 'gbm-contrato-intermediacion'],
    confidence: 0.84,
  },
  {
    id: 'mx-gbm-trading-portfolio',
    domain: 'investment_statement_mx',
    title: 'GBM Trading y portafolio',
    aliases: ['GBM Trading', 'Trading Pro', 'acciones', 'ETFs', 'portafolio GBM', 'valor de mercado'],
    summary: 'Cuenta de inversion bursatil de GBM. La extraccion debe distinguir valor de mercado, efectivo, instrumentos, rendimientos, comisiones y movimientos de compra/venta.',
    patterns: ['trading\\s+pro', 'acciones', '\\bETF', 'valor\\s+de\\s+mercado', 'portafolio', 'compra\\s+venta', 'casa\\s+de\\s+bolsa'],
    fields: ['portfolio_value', 'cash_balance', 'detected_instruments', 'period_return', 'commissions', 'trade_date'],
    sourceIds: ['gbm-products', 'gbm-trading', 'gbm-contrato-intermediacion', 'condusef-sipres'],
    confidence: 0.84,
  },
  {
    id: 'mx-gbm-trading-order',
    domain: 'investment_statement_mx',
    title: 'Ordenes y operaciones GBM Trading',
    aliases: ['orden limitada', 'orden de mercado', 'compra venta', 'Trading MX', 'Trading USA'],
    summary: 'Las operaciones de trading deben guardar mercado, instrumento, lado, cantidad, precio, comisiones y fecha de liquidacion para reconciliar portafolio y efectivo.',
    patterns: ['trading\\s+(mx|usa)', 'orden\\s+(limitada|mercado)', 'compra\\s+venta', 'precio\\s+de\\s+ejecuci[oó]n', 'fecha\\s+de\\s+liquidaci[oó]n'],
    fields: ['instrument_symbol', 'market', 'side', 'order_type', 'quantity', 'execution_price', 'commission', 'settlement_date'],
    sourceIds: ['gbm-trading', 'gbm-contrato-intermediacion', 'bmv-market-infrastructure'],
    confidence: 0.84,
  },
  {
    id: 'mx-investment-operations-csv',
    domain: 'investment_statement_mx',
    title: 'CSV de operaciones de inversion',
    aliases: ['CSV GBM', 'operaciones de inversion', 'fecha operacion', 'fecha liquidacion', 'ticker', 'titulos', 'comision'],
    summary: 'Los CSV de casas de bolsa y plataformas de inversion deben capturarse como evidencia de operaciones: compra/venta, ticker, mercado, titulos, precio, importe, comision, impuesto, moneda y liquidacion. La app los deja en revision para evitar que compras/ventas se mezclen con ingresos o gastos operativos.',
    patterns: ['fecha\\s+operaci[oó]n', 'fecha\\s+liquidaci[oó]n', 'ticker', 'emisora', 't[ií]tulos', 'precio', 'comisi[oó]n', 'compra|venta|dividendo'],
    fields: [
      'investmentOperationRows',
      'investmentOperationRowCount',
      'tradeDate',
      'settlementDate',
      'operationType',
      'ticker',
      'instrumentType',
      'market',
      'currency',
      'quantity',
      'price',
      'grossAmount',
      'commission',
      'commissionsAmount',
      'taxWithheld',
      'investmentCashFlow',
      'tickers',
    ],
    sourceIds: ['gbm-trading', 'gbm-contrato-intermediacion', 'bmv-market-infrastructure', 'cetesdirecto-productos'],
    confidence: 0.84,
  },
  {
    id: 'mx-bmv-market-infrastructure',
    domain: 'investment_statement_mx',
    title: 'Infraestructura bursatil BMV e Indeval',
    aliases: ['BMV', 'Bolsa Mexicana de Valores', 'Indeval', 'mercado de capitales', 'liquidacion de valores', 'SIC'],
    summary: 'La BMV publica informacion de mercados, brokers, regulacion, instrumentos, emisoras y empresas del grupo como Indeval. Para estados de cuenta bursatiles conviene separar mercado, instrumento, emisora/ticker, fecha de operacion, fecha de liquidacion, volumen, precio, comision e importe liquidado.',
    patterns: ['bolsa\\s+mexicana\\s+de\\s+valores', '\\bBMV\\b', '\\bIndeval\\b', 'mercado\\s+de\\s+capitales', 'sistema\\s+internacional\\s+de\\s+cotizaciones|\\bSIC\\b', 'liquidaci[oó]n\\s+de\\s+valores'],
    fields: ['market', 'instrumentType', 'ticker', 'issuer', 'tradeDate', 'settlementDate', 'titleCount', 'price', 'commission', 'settlementWindow'],
    sourceIds: ['bmv-market-infrastructure'],
    confidence: 0.78,
  },
  {
    id: 'mx-gbm-trading-cash-liquidity',
    domain: 'investment_statement_mx',
    title: 'GBM Trading, mercados y efectivo disponible',
    aliases: ['Trading MX', 'Trading USA', 'Disponible para comprar', 'capas de efectivo', 'liquidacion dolares', 'Smart Cash a Trading USA'],
    summary: 'GBM separa Trading MX/USA, efectivo disponible, conversiones y liquidacion. Para analisis financiero, transferencias entre Smart Cash y Trading son movimientos patrimoniales, no ingreso o gasto operativo.',
    patterns: ['trading\\s+(mx|usa)', 'disponible\\s+para\\s+comprar', 'capas\\s+de\\s+efectivo', 'liquidaci[oó]n\\s+de\\s+d[oó]lares', 'smart\\s+cash\\s+a\\s+trading'],
    fields: ['market', 'currency', 'available_to_invest', 'cash_balance', 'settlement_window', 'source_account', 'transfer_classification'],
    sourceIds: ['gbm-trading', 'gbm-smart-cash'],
    confidence: 0.86,
  },
  {
    id: 'mx-investment-fund-position',
    domain: 'investment_statement_mx',
    title: 'Fondos de inversion y series',
    aliases: ['fondo de inversion', 'Fondos GBM', 'fondos externos', 'serie', 'precio de valuacion'],
    summary: 'Los fondos deben capturarse por nombre, serie, titulos, precio de valuacion, fecha de valuacion, liquidez y ganancia/perdida no realizada.',
    patterns: ['fondos?\\s+(de\\s+inversi[oó]n|gbm|externos)', 'sociedad\\s+de\\s+inversi[oó]n', 'precio\\s+de\\s+valuaci[oó]n', '\\bserie\\b'],
    fields: ['fund_name', 'series', 'shares', 'price', 'valuation_date', 'unrealized_gain', 'liquidity'],
    sourceIds: ['gbm-trading', 'condusef-sipres'],
    confidence: 0.82,
  },
  {
    id: 'mx-gbm-ppr',
    domain: 'retirement_investment_mx',
    title: 'Plan Personal para el Retiro GBM',
    aliases: ['PPR', 'Plan Personal para el Retiro', 'plan personal de retiro', 'retiro GBM', 'aportacion deducible'],
    summary: 'Cuenta de inversion enfocada en retiro. Debe analizarse separada del ahorro liquido porque tiene objetivo, restricciones de retiro y tratamiento fiscal distinto.',
    patterns: ['\\bPPR\\b', 'plan\\s+personal\\s+(para|de)\\s+el\\s+retiro', 'aportaci[oó]n\\s+deducible', 'fecha\\s+objetivo\\s+de\\s+retiro'],
    fields: ['retirementProduct', 'retirementBalance', 'monthlyContribution', 'taxDeductibleAmount', 'targetRetirementDate', 'withdrawalRestriction', 'liquidityRestriction'],
    sourceIds: ['gbm-products', 'consar-cuenta-individual'],
    confidence: 0.78,
  },
  {
    id: 'mx-cetesdirecto-government-securities',
    domain: 'investment_statement_mx',
    title: 'Cetesdirecto y valores gubernamentales',
    aliases: ['Cetesdirecto', 'CETES', 'BONDES', 'UDIBONOS', 'Bonos', 'valores gubernamentales', 'fecha de vencimiento'],
    summary: 'Inversion directa en instrumentos gubernamentales. En estados debe capturarse instrumento, plazo, fecha de vencimiento, valor, tasa/rendimiento y liquidez.',
    patterns: ['cetesdirecto', '\\bCETES\\b', 'bondes', 'udibono', 'valor\\s+gubernamental', 'fecha\\s+de\\s+vencimiento', 'valor\\s+al\\s+vencimiento'],
    fields: ['investmentProduct', 'instrumentType', 'titleCount', 'maturityDate', 'termDays', 'portfolioValue', 'annualYieldPercent', 'periodReturn', 'maturityValue'],
    sourceIds: ['cetesdirecto-productos'],
    confidence: 0.86,
  },
  {
    id: 'mx-cetesdirecto-daily-funds',
    domain: 'investment_statement_mx',
    title: 'BONDDIA y ENERFIN en Cetesdirecto',
    aliases: ['BONDDIA', 'ENERFIN', 'fondos cetesdirecto', 'liquidez diaria', 'liquidacion 48 horas', 'disponible para retirar'],
    summary: 'BONDDIA y ENERFIN son fondos dentro de Cetesdirecto con reglas de liquidez y riesgo distintas a CETES. La app debe separarlos de valores gubernamentales para no confundir liquidez, plazo y riesgo.',
    patterns: ['bonddia', 'enerfin', 'liquidez\\s+diaria', 'liquidaci[oó]n\\s+a\\s+48\\s+horas', 'fondo\\s+de\\s+inversi[oó]n'],
    fields: ['fundName', 'dailyLiquidity', 'settlementWindow', 'riskLevel', 'portfolioValue', 'annualYieldPercent', 'availableToWithdraw', 'reviewRequired'],
    sourceIds: ['cetesdirecto-productos'],
    confidence: 0.86,
  },
  {
    id: 'mx-afore-account',
    domain: 'retirement_savings_mx',
    title: 'Cuenta individual Afore',
    aliases: ['AFORE', 'cuenta individual', 'ahorro para el retiro', 'CONSAR', 'SIEFORE', 'RCV'],
    summary: 'Cuenta de ahorro para el retiro administrada por una Afore. Para analisis financiero se debe separar de liquidez diaria y conservar aportaciones, rendimientos y subcuentas.',
    patterns: ['\\bAFORE\\b', 'cuenta\\s+individual', 'ahorro\\s+para\\s+el\\s+retiro', 'subcuenta', 'rendimiento\\s+neto', 'siefore', '\\bRCV\\b'],
    fields: ['retirementProduct', 'retirementBalance', 'voluntaryContributions', 'mandatoryContributions', 'periodReturn', 'subaccounts', 'siefore', 'weeksContributed'],
    sourceIds: ['consar-cuenta-individual'],
    confidence: 0.82,
  },
  {
    id: 'mx-afore-statement-movements',
    domain: 'retirement_savings_mx',
    title: 'Estado de cuenta AFORE, saldos y movimientos',
    aliases: ['estado de cuenta AFORE', 'saldos y movimientos', 'ahorro voluntario', 'subcuentas AFORE', 'retiro ahorro voluntario', 'aportaciones patronales', 'cuota social'],
    summary: 'Los estados AFORE deben modelarse como retiro/ahorro de largo plazo: saldos por subcuenta, aportaciones, retiros, rendimientos y ahorro voluntario, sin mezclarlo con liquidez diaria.',
    patterns: ['estado\\s+de\\s+cuenta\\s+afore', 'saldos\\s+y\\s+movimientos', 'ahorro\\s+voluntario', 'subcuentas?', 'retiro\\s+de\\s+ahorro\\s+voluntario'],
    fields: ['periodStart', 'periodEnd', 'retirementBalance', 'subaccounts', 'mandatoryContributions', 'voluntaryContributions', 'employerContributions', 'governmentContributions', 'retirementWithdrawals', 'periodReturn', 'longTermLiquidity'],
    sourceIds: ['consar-catalogo-tramites', 'consar-cuenta-individual'],
    confidence: 0.84,
  },
  {
    id: 'mx-payroll-bank-statement',
    domain: 'bank_statement_mx',
    title: 'Estado de cuenta de nomina bancaria mixta',
    aliases: ['cuenta nomina', 'estado de cuenta nomina', 'depositos nomina', 'retiros nomina', 'cuenta sueldo'],
    summary: 'Una cuenta de nomina bancaria no es CFDI: puede contener depositos de salario, retiros, pagos de tarjeta y transferencias. La direccion del movimiento manda sobre la palabra nomina.',
    patterns: ['cuenta\\s+n[oó]mina', 'estado\\s+de\\s+cuenta.*n[oó]mina', 'dep[oó]sitos?', 'retiros?', 'saldo\\s+(inicial|final|actual)'],
    fields: ['periodStart', 'periodEnd', 'depositRows', 'withdrawalRows', 'payrollDepositRows', 'payrollAccountMixedFlow', 'ambiguousDirectionRows', 'bankReconciliationStatus'],
    sourceIds: ['banxico-cep', 'sat-nomina-guia'],
    confidence: 0.86,
  },
  {
    id: 'mx-card-real-statement-layout',
    domain: 'credit_card_statement_mx',
    title: 'Layout real del estado universal de tarjeta',
    aliases: ['estado universal tarjeta', 'desglose de movimientos', 'cargos y abonos', 'compras diferidas', 'cargos no reconocidos'],
    summary: 'CONDUSEF define secciones de pago requerido, resumen de cargos/abonos, costo anual, nivel de uso, compras diferidas, desglose de movimientos y cargos no reconocidos.',
    patterns: ['pago\\s+requerido', 'resumen\\s+de\\s+cargos\\s+y\\s+abonos', 'desglose\\s+de\\s+movimientos', 'cargos\\s+no\\s+reconocidos', 'compras\\s+y\\s+cargos\\s+diferidos'],
    fields: ['periodStart', 'periodEnd', 'cutoffDate', 'dueDate', 'minimumPayment', 'minimumPaymentWithDeferred', 'noInterestPayment', 'creditLimit', 'availableCredit', 'cardMovementRows', 'cardReconciliationStatus'],
    sourceIds: ['condusef-estado-cuenta-tdc', 'condusef-glosario-tdc', 'banxico-comparador-creditos'],
    confidence: 0.9,
  },
  {
    id: 'mx-nu-sofipo-statement',
    domain: 'bank_statement_mx',
    title: 'Cuenta Nu, Cajitas y SOFIPO',
    aliases: ['Cuenta Nu', 'Cajitas Nu', 'Cajita Turbo', 'SOFIPO', 'GAT Nu', 'Fondo de Proteccion'],
    summary: 'Cuenta Nu/Cajitas debe capturar producto, GAT nominal/real, fecha de calculo, vigencia, rendimiento del periodo, limite de proteccion y movimientos internos sin tratarlos como gasto operativo.',
    patterns: ['cuenta\\s+nu', 'cajitas?', 'cajita\\s+turbo', 'gat\\s+nominal', 'gat\\s+real', 'fondo\\s+de\\s+protecci[oó]n', 'sofipo'],
    fields: ['savingsProduct', 'annualYieldPercent', 'nominalGatPercent', 'realGatPercent', 'yieldCalculationDate', 'yieldValidUntil', 'periodYield', 'protectionLimitUdis', 'frozenTermDays', 'statementMovementRows'],
    sourceIds: ['nu-mx-products', 'nu-cuenta', 'nu-gat', 'banxico-cep'],
    confidence: 0.88,
  },
  {
    id: 'mx-gbm-tax-and-trades',
    domain: 'investment_statement_mx',
    title: 'GBM operaciones, impuestos y liquidacion',
    aliases: ['GBM trades', 'constancia GBM', 'fecha de liquidacion', 'comision GBM', 'ISR retenido inversiones'],
    summary: 'Operaciones GBM requieren fecha de operacion/liquidacion, simbolo, mercado, moneda, cantidad, precio, comision, impuesto retenido y tipo de cambio para reconciliar portafolio y efectivo.',
    patterns: ['fecha\\s+de\\s+liquidaci[oó]n', 'comisi[oó]n', 'isr\\s+retenido', 'tipo\\s+de\\s+cambio', 'instrumento', 't[ií]tulos?', 'precio\\s+promedio'],
    fields: ['tradeDate', 'settlementDate', 'instrumentSymbol', 'market', 'currency', 'quantity', 'price', 'commission', 'taxWithheld', 'fxRate'],
    sourceIds: ['gbm-products', 'gbm-contrato-intermediacion'],
    confidence: 0.84,
  },
  {
    id: 'mx-cetesdirecto-ladder',
    domain: 'investment_statement_mx',
    title: 'Escalera de Cetesdirecto y reinversion',
    aliases: ['escalera CETES', 'reinversion cetes', 'fecha de vencimiento', 'valor nominal', 'valor al vencimiento'],
    summary: 'Cetesdirecto debe separar compra, liquidacion, vencimiento, plazo, titulos, valor nominal, precio de compra, valor al vencimiento, reinversion e ISR retenido.',
    patterns: ['fecha\\s+de\\s+compra', 'fecha\\s+de\\s+vencimiento', 'valor\\s+nominal', 'valor\\s+al\\s+vencimiento', 'reinversi[oó]n', 'plazo'],
    fields: ['instrumentType', 'purchaseDate', 'settlementDate', 'maturityDate', 'termDays', 'titleCount', 'purchaseValue', 'nominalValue', 'maturityValue', 'reinvestmentInstruction', 'taxWithheld'],
    sourceIds: ['cetesdirecto-productos'],
    confidence: 0.88,
  },
  {
    id: 'mx-afore-official-statement',
    domain: 'retirement_savings_mx',
    title: 'Estado de cuenta AFORE oficial',
    aliases: ['estado cuenta AFORE oficial', 'SIEFORE', 'indicador de rendimiento neto', 'comision AFORE', 'semanas cotizadas'],
    summary: 'Un estado AFORE real debe capturar periodo, AFORE, SIEFORE, subcuentas, aportaciones, retiros, rendimiento neto, comision, semanas cotizadas y tratarlo como retiro de largo plazo.',
    patterns: ['afore', 'siefore', 'rendimiento\\s+neto', 'comisi[oó]n', 'semanas\\s+cotizadas', 'subcuenta\\s+retiro', 'ahorro\\s+voluntario'],
    fields: ['aforeName', 'siefore', 'periodStart', 'periodEnd', 'subaccountRows', 'mandatoryContributions', 'voluntaryContributions', 'employerContributions', 'governmentContributions', 'netReturnIndicator', 'commissionRate', 'weeksContributed'],
    sourceIds: ['consar-cuenta-individual', 'consar-catalogo-tramites'],
    confidence: 0.86,
  },
  {
    id: 'mx-ppr-tax-treatment',
    domain: 'retirement_investment_mx',
    title: 'PPR y tratamiento fiscal',
    aliases: ['PPR deducible', 'plan personal retiro fiscal', 'tope deducible', 'retiro anticipado PPR'],
    summary: 'PPR debe separarse de AFORE y de liquidez diaria: contrato/proveedor, aportacion deducible, restricciones de retiro, objetivo de retiro, impuestos retenidos y reglas fiscales.',
    patterns: ['\\bPPR\\b', 'plan\\s+personal\\s+(para|de)\\s+el\\s+retiro', 'deducible', 'retiro\\s+anticipado', 'tratamiento\\s+fiscal'],
    fields: ['provider', 'contractType', 'taxDeductibleAmount', 'deductibilityCapBasis', 'withdrawalRestriction', 'targetRetirementDate', 'taxWithheld', 'liquidityRestriction'],
    sourceIds: ['diputados-lisr', 'gbm-products'],
    confidence: 0.8,
  },
]

export const knowledgeEntries = rawKnowledgeEntries.map(normalizeKnowledgeEntry)
