import type { ImportedDocument } from '../../domain/types'
import { documentKindLabels } from '../../lib/documentFieldSpecs'
import { documentQualitySummary } from './documentQuality'

export const extractedFieldLabels: Record<string, string> = {
  accountType: 'Cuenta',
  accountLast4: 'Terminacion',
  amount: 'Importe',
  ambiguousDirectionRows: 'Filas sin direccion',
  annualYieldPercent: 'Rendimiento anual',
  appliedRows: 'Movimientos aplicados',
  aforeDetected: 'AFORE detectado',
  aforeName: 'AFORE',
  availableCredit: 'Credito disponible',
  availableToInvest: 'Disponible invertir',
  availableToWithdraw: 'Disponible retirar',
  balance: 'Saldo',
  balancePendingReview: 'Saldo por revisar',
  balanceDetected: 'Saldo detectado',
  balanceDeltaDepositRows: 'Depositos por saldo',
  balanceDeltaInferredRows: 'Inferidos por saldo',
  balanceDeltaWithdrawalRows: 'Retiros por saldo',
  bankBalanceDifference: 'Diferencia banco',
  bankReconciliationStatus: 'Conciliacion banco',
  baseContributionSalary: 'SBC',
  cashBalance: 'Efectivo',
  catPercent: 'CAT',
  closingBalance: 'Saldo final',
  credit: 'Credito',
  creditLimit: 'Limite credito',
  currentBalance: 'Saldo actual',
  cutoffDate: 'Fecha corte',
  date: 'Fecha',
  dedupeReason: 'Razon dedupe',
  detectedFields: 'Campos detectados',
  detectedInstruments: 'Instrumentos',
  deposit: 'Deposito',
  depositRows: 'Mov. deposito',
  depositsTotal: 'Depositos',
  debtPaymentRows: 'Pagos deuda',
  debtPaymentTotal: 'Total pagos deuda',
  deferredAmortization: 'Diferidos del periodo',
  deferredDetected: 'Diferidos',
  description: 'Descripcion',
  dueDate: 'Fecha limite',
  employerName: 'Emisor nomina',
  expectedClosingBalance: 'Saldo final esperado',
  expectedFields: 'Campos esperados',
  expenseRows: 'Mov. gasto',
  expenseTotal: 'Total gastos',
  employeeCurpSuffix: 'CURP terminacion',
  employeeNssSuffix: 'NSS terminacion',
  employeeNumberSuffix: 'Empleado terminacion',
  employeeRfcSuffix: 'RFC receptor',
  employerRfcSuffix: 'RFC emisor',
  employerRegistrationSuffix: 'Registro patronal',
  employmentRegime: 'Regimen',
  employmentSubsidyAmount: 'Subsidio empleo',
  bankCode: 'Banco',
  cardReconciliationDifference: 'Diferencia conciliacion',
  cardReconciliationExpectedBalance: 'Saldo esperado',
  cardReconciliationMissing: 'Faltan para conciliar',
  cardReconciliationSeverity: 'Riesgo conciliacion',
  cardReconciliationStatus: 'Conciliacion tarjeta',
  cardReconciliationTolerance: 'Tolerancia',
  cardChargesRows: 'Mov. cargo tarjeta',
  cardChargesTotal: 'Cargos visibles',
  cardActivityRows: 'Mov. actividad',
  cardActivityDates: 'Fechas actividad',
  cardActivityDescriptions: 'Descripciones actividad',
  cardActivityAmounts: 'Montos actividad',
  cardActivityCurrency: 'Moneda actividad',
  cardCreditsRows: 'Mov. credito tarjeta',
  cardCreditsTotal: 'Creditos visibles',
  cardMovementRowCount: 'Movimientos tarjeta',
  cardMovementRows: 'Detalle tarjeta',
  cardMovementExtractionMethod: 'Método de extracción',
  cardMovementCoordinateHeaderPages: 'Páginas con tabla detectada',
  cardNetActivity: 'Actividad neta tarjeta',
  cardPaymentsRows: 'Mov. pago tarjeta',
  cardPaymentsTotal: 'Pagos visibles',
  cardLowestEstimatedInterest: 'Menor interes estimado',
  cardLowestInterestScenario: 'Mejor escenario',
  cardMaxInterestSavings: 'Ahorro maximo interes',
  cardPaymentScenarioRows: 'Escenarios pago',
  cardPaymentScenarios: 'Escenarios detalle',
  charge: 'Cargo',
  compensatedBalance: 'Saldo favor',
  contractType: 'Contrato',
  conflictingAmountRows: 'Filas ambiguas',
  contributions: 'Aportaciones',
  deductionConcepts: 'Deducciones detalle',
  dailyIntegratedSalary: 'SDI',
  dailyReturn: 'Rendimiento diario',
  feesAmount: 'Comisiones',
  financialCostsTotal: 'Costo financiero',
  frozenSavingsDetected: 'Ahorro congelado',
  frozenTermDays: 'Plazo congelado',
  grossPay: 'Percepciones',
  imssDetected: 'IMSS',
  infonavitDetected: 'INFONAVIT',
  interestAmount: 'Intereses',
  incomeRows: 'Mov. ingreso',
  incomeTotal: 'Total ingresos',
  instrumentCount: 'Instrumentos detectados',
  investmentProduct: 'Producto inversion',
  investmentWithdrawalsTotal: 'Retiros inversion',
  isrDetected: 'ISR',
  isrWithheld: 'ISR retenido',
  iva: 'IVA',
  issuerName: 'Emisor',
  liquidity: 'Liquidez',
  matchedTransactionIds: 'Movimientos relacionados',
  merchant: 'Comercio',
  movementType: 'Tipo movimiento',
  name: 'Nombre',
  minimumPayment: 'Pago minimo',
  minimumPaymentWithDeferred: 'Minimo + diferidos',
  missingFields: 'Campos faltantes',
  netCashFlow: 'Flujo neto',
  netIncome: 'Ingreso neto',
  newCharges: 'Cargos',
  nominalGatPercent: 'GAT nominal',
  noInterestPayment: 'Pago no intereses',
  ocrConfidence: 'Confianza OCR',
  openingBalance: 'Saldo inicial',
  ordinaryAnnualRate: 'Tasa anual',
  otherPaymentConcepts: 'Otros pagos detalle',
  payment: 'Pago',
  paymentsAmount: 'Pagos',
  paymentDate: 'Fecha pago',
  estimatedInterest: 'Interes estimado',
  estimatedTotalCost: 'Costo total estimado',
  paidDays: 'Dias pagados',
  pagesWithLayoutText: 'Paginas con texto',
  pagesWithOcrText: 'Paginas OCR',
  payrollAccountDepositRows: 'Depositos cuenta nomina',
  payrollAccountMixedFlow: 'Cuenta nomina mixta',
  payrollAccountWithdrawalRows: 'Retiros cuenta nomina',
  payrollComplementVersion: 'Version nomina',
  payrollDepositRows: 'Depositos nomina',
  payrollDepositTotal: 'Total nomina',
  payrollPeriodicity: 'Periodicidad',
  periodYield: 'Rendimiento periodo',
  payrollType: 'Tipo nomina',
  payrollUuidSuffix: 'UUID terminacion',
  periodEnd: 'Fin periodo',
  periodReturn: 'Rendimiento',
  periodStart: 'Inicio periodo',
  pdfTextMode: 'Lectura PDF',
  pdfTextPagesRead: 'Paginas leidas',
  portfolioValue: 'Valor portafolio',
  positionRows: 'Posiciones',
  positions: 'Detalle posiciones',
  positionsMarketValue: 'Valor posiciones',
  price: 'Precio',
  perceptionConcepts: 'Percepciones detalle',
  previousBalance: 'Saldo anterior',
  quantity: 'Cantidad',
  qualityScore: 'Calidad',
  receiverName: 'Receptor',
  realGatPercent: 'GAT real',
  reviewedMovementRowsApplied: 'Movimientos PDF aplicados',
  reviewedMovementRowsAppliedAt: 'PDF aplicado',
  reviewedMovementRowsApproval: 'Aprobacion PDF',
  rows: 'Filas',
  savingsProduct: 'Producto ahorro',
  skippedDuplicateRows: 'Duplicados omitidos',
  skippedRows: 'Filas omitidas',
  skippedSemanticDuplicates: 'Nomina no duplicada',
  settlementWindow: 'Liquidacion',
  scenarioName: 'Escenario',
  speiDetected: 'SPEI detectado',
  speiBeneficiaryAccountLast4: 'Cuenta beneficiaria',
  speiIssuerInstitution: 'Banco emisor SPEI',
  speiPaymentAmount: 'Monto SPEI',
  speiReceiverInstitution: 'Banco receptor SPEI',
  speiReferenceNumber: 'Referencia SPEI',
  speiTraceKey: 'Clave rastreo',
  statementDate: 'Fecha estado',
  statementMovementDepositRows: 'Depositos visibles',
  statementMovementDepositsTotal: 'Depositos PDF',
  statementMovementNetCashFlow: 'Flujo visible PDF',
  statementMovementRowCount: 'Movimientos visibles',
  statementMovementRows: 'Detalle movimientos',
  statementMovementWithdrawalRows: 'Retiros visibles',
  statementMovementWithdrawalsTotal: 'Retiros PDF',
  subtotal: 'Subtotal',
  textPreview: 'Texto OCR',
  textLength: 'Texto',
  total: 'Total',
  totalDeducciones: 'Deducciones',
  totalDebtBalance: 'Saldo deudor',
  totalOtrosPagos: 'Otros pagos',
  totalPercepciones: 'Percepciones',
  totalPerceptionsExempt: 'Exento',
  totalPerceptionsTaxable: 'Gravado',
  totalDeductions: 'Deducciones',
  totalOtherDeductions: 'Otras deducciones',
  totalOtherPayments: 'Otros pagos',
  totalSalaries: 'Sueldos',
  totalTaxesWithheld: 'Impuestos retenidos',
  taxWithheld: 'Impuesto retenido',
  imssWithheld: 'IMSS retenido',
  infonavitWithheld: 'INFONAVIT',
  investmentBuyRows: 'Compras inversion',
  investmentCashFlow: 'Flujo inversion',
  investmentFeeRows: 'Comisiones inversion',
  investmentIncomeRows: 'Ingresos inversion',
  investmentOperationRowCount: 'Operaciones inversion',
  investmentOperationRows: 'Detalle operaciones',
  investmentSellRows: 'Ventas inversion',
  markets: 'Mercados',
  tickers: 'Tickers',
  tradedAmount: 'Importe operado',
  workdayType: 'Jornada',
  yieldCalculationDate: 'Calculo rendimiento',
  yieldValidUntil: 'Vigencia rendimiento',
  riskPosition: 'Riesgo puesto',
  federalEntity: 'Entidad',
  unparsedDates: 'Fechas no leidas',
  vatAmount: 'IVA',
  transferRows: 'Transferencias',
  transferInTotal: 'Transferencias entrada',
  transferOutTotal: 'Transferencias salida',
  withdrawalRows: 'Mov. retiro',
  withdrawal: 'Retiro',
  withdrawals: 'Retiros',
  withdrawalsTotal: 'Retiros',
  commissionsAmount: 'Comisiones inversion',
  contributionsTotal: 'Aportaciones',
  curpSuffix: 'CURP terminacion',
  market: 'Mercado',
  minimumAmount: 'Monto minimo',
  monthlyContribution: 'Aportacion mensual',
  monthlyDepositLimitUdis: 'Limite mensual UDIs',
  mandatoryContributions: 'Aport. obligatorias',
  maturityDate: 'Vencimiento',
  maturityValue: 'Valor vencimiento',
  marketValue: 'Valor mercado',
  netReturnIndicator: 'Rendimiento neto',
  nativeTextItems: 'Items texto PDF',
  nominalValue: 'Valor nominal',
  nonDeductibleContributions: 'Aport. no deducibles',
  protectionLimitUdis: 'Proteccion UDIs',
  purchaseDate: 'Fecha compra',
  unrealizedGain: 'Ganancia no realizada',
  employerContributions: 'Aport. patronales',
  fundName: 'Fondo',
  governmentContributions: 'Aport. gobierno',
  instrumentType: 'Instrumento',
  liquidityRestriction: 'Restriccion liquidez',
  longTermLiquidity: 'Liquidez largo plazo',
  nssSuffix: 'NSS terminacion',
  retirementBalance: 'Saldo retiro',
  retirementProduct: 'Producto retiro',
  retirementWithdrawals: 'Retiros retiro',
  riskLevel: 'Riesgo',
  siefore: 'SIEFORE',
  subaccounts: 'Subcuentas',
  subaccountBalanceTotal: 'Saldo subcuentas',
  subaccountPositions: 'Detalle subcuentas',
  subaccountRows: 'Subcuentas detalle',
  targetRetirementDate: 'Fecha objetivo retiro',
  taxDeductibleAmount: 'Deducible',
  termDays: 'Plazo dias',
  titleCount: 'Titulos',
  voluntaryContributions: 'Aport. voluntarias',
  weeksContributed: 'Semanas cotizadas',
  withdrawalRestriction: 'Restriccion retiro',
}

const moneyFields = new Set([
  'amount',
  'availableCredit',
  'availableToInvest',
  'availableToWithdraw',
  'bankBalanceDifference',
  'balance',
  'baseContributionSalary',
  'cashBalance',
  'cardReconciliationDifference',
  'cardReconciliationExpectedBalance',
  'cardReconciliationTolerance',
  'cardChargesTotal',
  'cardCreditsTotal',
  'cardNetActivity',
  'cardPaymentsTotal',
  'charge',
  'closingBalance',
  'credit',
  'creditLimit',
  'currentBalance',
  'debtPaymentTotal',
  'deferredAmortization',
  'deposit',
  'depositsTotal',
  'dailyIntegratedSalary',
  'dailyReturn',
  'employmentSubsidyAmount',
  'compensatedBalance',
  'commissionsAmount',
  'contributions',
  'contributionsTotal',
  'employerContributions',
  'expectedClosingBalance',
  'expenseTotal',
  'feesAmount',
  'financialCostsTotal',
  'grossPay',
  'governmentContributions',
  'imssWithheld',
  'infonavitWithheld',
  'interestAmount',
  'estimatedInterest',
  'estimatedTotalCost',
  'incomeTotal',
  'investmentWithdrawalsTotal',
  'isrWithheld',
  'minimumPayment',
  'minimumPaymentWithDeferred',
  'minimumAmount',
  'monthlyPayment',
  'monthlyContribution',
  'mandatoryContributions',
  'maturityValue',
  'marketValue',
  'netCashFlow',
  'netIncome',
  'newCharges',
  'noInterestPayment',
  'cardLowestEstimatedInterest',
  'cardMaxInterestSavings',
  'nominalValue',
  'nonDeductibleContributions',
  'openingBalance',
  'paymentsAmount',
  'payment',
  'payrollDepositTotal',
  'periodYield',
  'periodReturn',
  'portfolioValue',
  'positionsMarketValue',
  'price',
  'previousBalance',
  'purchaseValue',
  'retirementBalance',
  'retirementWithdrawals',
  'speiPaymentAmount',
  'statementMovementDepositsTotal',
  'statementMovementNetCashFlow',
  'statementMovementWithdrawalsTotal',
  'subaccountBalanceTotal',
  'subtotal',
  'total',
  'totalDebtBalance',
  'totalDeducciones',
  'totalDeductions',
  'totalOtrosPagos',
  'totalOtherPayments',
  'totalPercepciones',
  'totalPerceptionsExempt',
  'totalPerceptionsTaxable',
  'vatAmount',
  'totalOtherDeductions',
  'totalSalaries',
  'totalTaxesWithheld',
  'taxWithheld',
  'taxDeductibleAmount',
  'transferInTotal',
  'transferOutTotal',
  'withdrawal',
  'withdrawalsTotal',
  'withdrawals',
  'unrealizedGain',
  'voluntaryContributions',
])

const percentFields = new Set([
  'annualYieldPercent',
  'catPercent',
  'netReturnIndicator',
  'nominalGatPercent',
  'ocrConfidence',
  'ordinaryAnnualRate',
  'qualityScore',
  'realGatPercent',
])

const extractedFieldPriority: Record<string, string[]> = {
  payroll_cfdi: [
    'paymentDate',
    'periodStart',
    'periodEnd',
    'employerName',
    'netIncome',
    'totalPercepciones',
    'totalDeducciones',
    'totalOtrosPagos',
    'isrWithheld',
    'imssWithheld',
    'infonavitWithheld',
    'payrollType',
    'payrollComplementVersion',
    'payrollPeriodicity',
    'paidDays',
    'employeeRfcSuffix',
    'employeeCurpSuffix',
    'payrollUuidSuffix',
    'appliedRows',
    'skippedSemanticDuplicates',
    'matchedTransactionIds',
    'grossPay',
    'totalDeductions',
    'isrDetected',
    'imssDetected',
    'infonavitDetected',
    'qualityScore',
    'missingFields',
  ],
  credit_card_statement: [
    'pdfTextMode',
    'pdfTextPagesRead',
    'pdfSummaryPagesRead',
    'documentSubtypeLabel',
    'cardActivityRows',
    'cardActivityDates',
    'cardActivityDescriptions',
    'cardActivityAmounts',
    'cardActivityCurrency',
    'cutoffDate',
    'dueDate',
    'minimumPayment',
    'minimumPaymentWithDeferred',
    'noInterestPayment',
    'cardPaymentScenarioRows',
    'cardLowestInterestScenario',
    'cardLowestEstimatedInterest',
    'cardMaxInterestSavings',
    'currentBalance',
    'cardReconciliationStatus',
    'cardReconciliationDifference',
    'cardReconciliationExpectedBalance',
    'creditLimit',
    'availableCredit',
    'previousBalance',
    'newCharges',
    'deferredAmortization',
 'paymentsAmount',
 'cardMovementRowCount',
 'cardMovementExtractionMethod',
 'cardMovementCoordinateHeaderPages',
 'cardChargesTotal',
    'cardPaymentsTotal',
    'cardCreditsTotal',
    'cardNetActivity',
    'financialCostsTotal',
    'interestAmount',
    'feesAmount',
    'vatAmount',
    'catPercent',
    'pagesWithLayoutText',
    'pagesWithOcrText',
    'qualityScore',
    'missingFields',
  ],
  bank_statement: [
    'pdfTextMode',
    'pdfTextPagesRead',
    'closingBalance',
    'savingsProduct',
    'annualYieldPercent',
    'nominalGatPercent',
    'realGatPercent',
    'bankReconciliationStatus',
    'depositsTotal',
    'withdrawalsTotal',
    'netCashFlow',
    'statementMovementRowCount',
    'payrollDepositRows',
    'payrollAccountMixedFlow',
    'payrollAccountDepositRows',
    'payrollAccountWithdrawalRows',
    'payrollDepositTotal',
    'depositRows',
    'withdrawalRows',
    'balanceDeltaInferredRows',
    'balanceDeltaDepositRows',
    'balanceDeltaWithdrawalRows',
    'ambiguousDirectionRows',
    'debtPaymentRows',
    'transferRows',
    'incomeRows',
    'expenseRows',
    'openingBalance',
    'expectedClosingBalance',
    'bankBalanceDifference',
    'appliedRows',
    'skippedSemanticDuplicates',
    'periodYield',
    'frozenTermDays',
    'yieldCalculationDate',
    'yieldValidUntil',
    'protectionLimitUdis',
    'speiDetected',
    'speiTraceKey',
    'speiPaymentAmount',
    'speiBeneficiaryAccountLast4',
    'pagesWithLayoutText',
    'pagesWithOcrText',
    'qualityScore',
    'missingFields',
  ],
  investment_statement: [
    'investmentProduct',
    'retirementProduct',
    'portfolioValue',
    'retirementBalance',
    'instrumentType',
    'maturityDate',
    'termDays',
    'titleCount',
    'positionRows',
    'positionsMarketValue',
    'maturityValue',
    'marketValue',
    'availableToWithdraw',
    'cashBalance',
    'availableToInvest',
    'investmentOperationRowCount',
    'tradedAmount',
    'investmentCashFlow',
    'investmentBuyRows',
    'investmentSellRows',
    'tickers',
    'periodReturn',
    'dailyReturn',
    'annualYieldPercent',
    'netReturnIndicator',
    'subaccounts',
    'subaccountRows',
    'subaccountBalanceTotal',
    'siefore',
    'weeksContributed',
    'voluntaryContributions',
    'mandatoryContributions',
    'employerContributions',
    'governmentContributions',
    'retirementWithdrawals',
    'monthlyContribution',
    'taxDeductibleAmount',
    'currency',
    'market',
    'liquidity',
    'settlementWindow',
    'dailyLiquidity',
    'longTermLiquidity',
    'riskLevel',
    'detectedInstruments',
    'commissionsAmount',
    'taxWithheld',
    'qualityScore',
    'missingFields',
  ],
  invoice_cfdi: ['issuerName', 'receiverName', 'subtotal', 'iva', 'total', 'appliedRows', 'skippedDuplicateRows', 'matchedTransactionIds', 'qualityScore', 'missingFields'],
  purchase_receipt: ['merchant', 'date', 'total', 'iva', 'appliedRows', 'skippedDuplicateRows', 'ocrConfidence', 'qualityScore'],
  unknown: ['qualityScore', 'textLength', 'missingFields'],
}

const safePreviewFields = new Set([
  'accountLast4',
  'accountType',
  'ambiguousDirectionRows',
  'annualYieldPercent',
  'appliedRows',
  'availableCredit',
  'availableToInvest',
  'availableToWithdraw',
  'balance',
  'balancePendingReview',
  'balanceDetected',
  'bankBalanceDifference',
  'bankReconciliationStatus',
  'balanceDeltaDepositRows',
  'balanceDeltaInferredRows',
  'balanceDeltaWithdrawalRows',
  'baseContributionSalary',
  'cardReconciliationDifference',
  'cardReconciliationStatus',
  'cardLowestInterestScenario',
  'cardMaxInterestSavings',
  'cashBalance',
  'catPercent',
  'closingBalance',
  'creditLimit',
  'currentBalance',
  'cutoffDate',
  'debtPaymentRows',
  'deductionConcepts',
  'detectedFields',
  'depositRows',
  'depositsTotal',
  'documentSubtypeLabel',
  'employerName',
  'expectedClosingBalance',
  'expectedFields',
  'feesAmount',
  'financialCostsTotal',
  'grossAmount',
  'incomeRows',
  'interestAmount',
  'investmentProduct',
  'investmentBuyRows',
  'investmentIncomeRows',
  'investmentOperationRowCount',
  'investmentSellRows',
  'isrWithheld',
  'mandatoryContributions',
  'maturityDate',
  'minimumPayment',
  'missingFields',
  'monthlyContribution',
  'netAmount',
  'netCashFlow',
  'netIncome',
  'newCharges',
  'noInterestPayment',
  'nominalGatPercent',
  'openingBalance',
  'paidDays',
  'paymentsAmount',
  'paymentDate',
  'payrollAccountDepositRows',
  'payrollAccountMixedFlow',
  'payrollAccountWithdrawalRows',
  'payrollDepositRows',
  'payrollComplementVersion',
  'payrollPeriodicity',
  'payrollType',
  'pdfTextMode',
  'pdfTextPagesRead',
  'periodEnd',
  'periodStart',
  'periodYield',
  'perceptionConcepts',
  'portfolioValue',
  'positionRows',
  'positionsMarketValue',
  'qualityScore',
  'realGatPercent',
  'requiresRawReimport',
  'retirementBalance',
  'retirementProduct',
  'retirementWithdrawals',
  'savingsProduct',
  'statementMovementRows',
  'subaccountBalanceTotal',
  'subaccountRows',
  'subaccounts',
  'taxDeductibleAmount',
  'taxWithheld',
  'textLength',
  'total',
  'totalDeducciones',
  'totalOtherDeductions',
  'totalPercepciones',
  'tradedAmount',
  'transferRows',
  'vatAmount',
  'voluntaryContributions',
  'weeksContributed',
  'withdrawalsTotal',
  'withdrawalRows',
])

const sensitiveDetailFields = new Set(['concept', 'description', 'key', 'name', 'reference', 'ticker'])

export function isSensitiveDetailField(key: string): boolean {
  return sensitiveDetailFields.has(key)
}

export function formatExtractedValue(key: string, value: unknown) {
  if (typeof value === 'boolean') return value ? 'si' : 'no'
  if ((key === 'cardReconciliationStatus' || key === 'bankReconciliationStatus') && typeof value === 'string') {
    if (value === 'balanced') return 'cuadra'
    if (value === 'mismatch') return 'no cuadra'
    return 'faltan datos'
  }
  if (key === 'cardReconciliationSeverity' && typeof value === 'string') {
    if (value === 'ok') return 'bajo'
    if (value === 'high') return 'alto'
    return 'medio'
  }
  if (typeof value === 'number') {
    if (moneyFields.has(key)) {
      return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 0 }).format(value)
    }
    if (percentFields.has(key)) {
      const normalized = value <= 1 ? value * 100 : value
      const precision = ['annualYieldPercent', 'nominalGatPercent', 'ordinaryAnnualRate', 'realGatPercent'].includes(key) ? 1 : normalized >= 10 ? 0 : 1
      return `${normalized.toFixed(precision)}%`
    }
    return Number.isInteger(value) ? String(value) : value.toFixed(value < 1 ? 2 : 2)
  }
  if (typeof value === 'string') return value
  if (key === 'matchedTransactionIds' && Array.isArray(value)) return `${value.length} movimiento(s)`
  if (Array.isArray(value)) return value.every((item) => typeof item === 'string') ? value.join(', ') : `${value.length} elemento(s)`
  return ''
}

export function extractedPreviewEntries(doc: ImportedDocument) {
  const extracted = doc.extracted ?? {}
  const priority = extractedFieldPriority[doc.kind ?? 'unknown'] ?? []
  const orderedKeys = [...priority, ...Object.keys(extracted).filter((key) => !priority.includes(key))]
  return orderedKeys
    .filter((key) => safePreviewFields.has(key))
    .map((key) => [key, extracted[key]] as const)
    .map(([key, value]) => [key, formatExtractedValue(key, value)] as const)
    .filter(([, value]) => value)
    .slice(0, 20)
}

export function safeDocumentTitle(doc: ImportedDocument, index: number) {
  return `${documentKindLabels[doc.kind ?? 'unknown']} ${index + 1}`
}

export function safeDocumentSummary(doc: ImportedDocument) {
  const quality = documentQualitySummary(doc)
  const rowLabel = doc.extractedRows === 1 ? 'partida detectada' : 'partidas detectadas'
  return `${documentKindLabels[doc.kind ?? 'unknown']} ${doc.status}; ${doc.extractedRows} ${rowLabel}; campos clave ${quality.detectedFields}/${quality.expectedFields || 0}.`
}

export type ExtractedDetailColumn = {
  key: string
  label: string
}

export const positionColumns: ExtractedDetailColumn[] = [
  { key: 'name', label: 'Nombre' },
  { key: 'instrumentType', label: 'Tipo' },
  { key: 'quantity', label: 'Cantidad' },
  { key: 'price', label: 'Precio' },
  { key: 'marketValue', label: 'Valor' },
  { key: 'unrealizedGain', label: 'Ganancia' },
]

export const subaccountColumns: ExtractedDetailColumn[] = [
  { key: 'name', label: 'Subcuenta' },
  { key: 'balance', label: 'Saldo' },
  { key: 'contributions', label: 'Aportaciones' },
  { key: 'withdrawals', label: 'Retiros' },
  { key: 'periodReturn', label: 'Rendimiento' },
]

export const investmentOperationColumns: ExtractedDetailColumn[] = [
  { key: 'tradeDate', label: 'Operacion' },
  { key: 'settlementDate', label: 'Liquidacion' },
  { key: 'operationType', label: 'Tipo' },
  { key: 'ticker', label: 'Ticker' },
  { key: 'market', label: 'Mercado' },
  { key: 'quantity', label: 'Titulos' },
  { key: 'price', label: 'Precio' },
  { key: 'grossAmount', label: 'Importe' },
  { key: 'commission', label: 'Comision' },
  { key: 'taxWithheld', label: 'ISR' },
  { key: 'cashFlow', label: 'Flujo' },
]

export const statementMovementColumns: ExtractedDetailColumn[] = [
  { key: 'date', label: 'Fecha' },
  { key: 'description', label: 'Concepto' },
  { key: 'deposit', label: 'Deposito' },
  { key: 'withdrawal', label: 'Retiro' },
  { key: 'balance', label: 'Saldo' },
  { key: 'movementType', label: 'Tipo' },
  { key: 'category', label: 'Categoria' },
]

export const cardMovementColumns: ExtractedDetailColumn[] = [
  { key: 'date', label: 'Fecha' },
  { key: 'description', label: 'Concepto' },
  { key: 'charge', label: 'Cargo' },
  { key: 'payment', label: 'Pago' },
  { key: 'credit', label: 'Credito' },
  { key: 'balance', label: 'Saldo' },
  { key: 'movementType', label: 'Tipo' },
  { key: 'category', label: 'Categoria' },
]

export const cardPaymentScenarioColumns: ExtractedDetailColumn[] = [
  { key: 'scenarioName', label: 'Escenario' },
  { key: 'monthlyPayment', label: 'Pago mensual' },
  { key: 'monthsToPayoff', label: 'Meses' },
  { key: 'estimatedInterest', label: 'Interes estimado' },
  { key: 'estimatedTotalCost', label: 'Costo total' },
]

export const payrollPerceptionColumns: ExtractedDetailColumn[] = [
  { key: 'type', label: 'Tipo' },
  { key: 'key', label: 'Clave' },
  { key: 'concept', label: 'Concepto' },
  { key: 'amount', label: 'Importe' },
  { key: 'taxable', label: 'Gravado' },
  { key: 'exempt', label: 'Exento' },
]

export const payrollConceptColumns: ExtractedDetailColumn[] = [
  { key: 'type', label: 'Tipo' },
  { key: 'key', label: 'Clave' },
  { key: 'concept', label: 'Concepto' },
  { key: 'amount', label: 'Importe' },
]

export function extractedObjectRows(doc: ImportedDocument, key: string): Array<Record<string, unknown>> {
  const value = doc.extracted?.[key]
  if (!Array.isArray(value)) return []
  return value.filter((row): row is Record<string, unknown> => Boolean(row) && typeof row === 'object' && !Array.isArray(row))
}
